### ISSUE TITLE
Update signature for `bentoml.load` in operators

### ISSUE THREAD

**Issue by jjmachan** [bentoml/bentoctl#139]

**Comment by yubozhao** [comment]
This only apply for AWS lambda and Azure functions

**Comment by yubozhao** [comment]
Let's use `load_bento_dir` method to be more explicit 

https://github.com/bentoml/BentoML/blob/ff702f1fc1ee7cc4cf7aab2e67d1e27512858fe4/bentoml/_internal/service/loader.py#L207

**Comment by jjmachan** [comment]
since load_bento_dir is internal, decided to keep using the `bentoml.load()` function

closing the issue is okay @yubozhao @parano
