### ISSUE TITLE
Error [BentoctlDockerException]:  Failed to tag Docker image, google-compute-engine-iris_classifier:6rqjqqbhbsscvnjh not found.

### ISSUE THREAD

**Issue by math-sasso** [bentoml/bentoctl#189]
**Describe the bug*
When I call `bentoctl build` as the command below to push an image to my container registry I am always getting this same error. 
```
bentoctl build -b iris_classifier:6rqjqqbhbsscvnjh -f deployment_config.yaml
```
```
Created the repository outside-venv-test
Error [BentoctlDockerException]:  Failed to tag Docker image, google-compute-engine-iris_classifier:6rqjqqbhbsscvnjh not found.
```

**To Reproduce**

What is curios is that my teammates can run it in their computers. My machine is a Ubuntu 20.04. 
I installed docker, gcloud and terraform according to those tools documentation

Follow the bentoml tutorial runnning those steps.

1. bentoml build
2. git clone https://github.com/bentoml/google-compute-engine-deploy.git
3. bentoctl operator install google-compute-engine-deploy
4. bentoctl build -b iris_classifier:6rqjqqbhbsscvnjh -f deployment_config.yaml
5. see error

![image](https://user-images.githubusercontent.com/23565626/187095483-22006b4b-6932-4694-89f8-0fac5863ab76.png)

**Environment:**
 - OS: [Ubuntu 30.04]
 - Python Version [e.g. Python 3.8.10]
 - BentoML Version [e.g. BentoML-1.0.4]
 - Bentoctl Version [e.g. bentoctl-0..3.3]
 - [google-compute-engine-deploy](https://github.com/bentoml/google-compute-engine-deploy)  [v.1.0.2]

**Comment by math-sasso** [comment]
My work around is to first call docker containerize to create a docker image and after tag the image in the format expected by bentoctl. This should be dont automatically by bentoctl, I still dont know the reason it fails. 

```
bentoml containerize iris_classifier:6rqjqqbhbsscvnjh
docker tag iris_classifier:6rqjqqbhbsscvnjh google-compute-engine-iris_classifier:6rqjqqbhbsscvnjh
```

**Comment by dbuades** [comment]
I found the same problem today using https://github.com/bentoml/aws-ec2-deploy

**Comment by jjmachan** [comment]
This issue should now be fixed in the main branch. @math-sasso @dbuades can you try it out and verify if that works for you? The installation instructions are mentioned here https://github.com/bentoml/bentoctl/blob/main/DEVELOPMENT.md#install-bentoctl-from-source  

and thank you for reporting this issue. if this fixes your issue we cut a new release for this fix.

**Comment by jjmachan** [comment]
PR #187 should have fixed this

**Comment by dbuades** [comment]
@jjmachan I confirm this fixes the issue, thanks! Sorry for the delay

**Comment by jjmachan** [comment]
thanks for confirming @dbuades. Closing this issue now
